apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asdsad
spec:
  type: service
  owner: hydris_team_3_-_tech_lead
  lifecycle: development

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: asd
spec:
  type: ""
